### ISSUE TITLE
Python 3.10+

### ISSUE THREAD

**Issue by mattwthompson** [jthorton/de-forcefields#2]
I'm curious if this [version](https://github.com/jthorton/de-forcefields/blob/aaaa4c721967310ec8e9e3176b97de858273b2d5/setup.cfg#L43-L44) constraint could be relaxed? It's preventing `pip install git+...` in my tests, probably because 0.10.6 is less tested on 3.10? I can work around it but I'd like to use this package directly if possible.

**Comment by jthorton** [comment]
Sure this seems to work now, in testing I had an issue with the toolkit not finding the installed force fields as the return from entry points had changed in 3.10.

**Comment by mattwthompson** [comment]
Thanks!
